# Generated by Django 4.2 on 2023-04-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('contato', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF')], max_length=50)),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('ENG', 'Inglês')], max_length=50)),
                ('ano_publicacao', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_created=True)),
                ('reservado_ate', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('status_resreva', models.CharField(choices=[('No prazo', 'No prazo'), ('Devolvido', 'Devolvido'), ('Em atraso', 'Em atraso')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LivroFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reservado', 'Reservado'), ('Disponível', 'Disponível')], max_length=50)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('ref_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
        ),
    ]
