# Generated by Django 4.2 on 2023-04-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_autor_descricao_alter_livro_ano_publicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='status_resreva',
            new_name='status_reserva',
        ),
    ]
