# Generated by Django 4.2 on 2023-04-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_rename_status_resreva_reserva_status_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default='000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='leitor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.leitor'),
            preserve_default=False,
        ),
    ]
